services:
  - type: web
    name: mlb-scorecards-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build --workspace backend
    startCommand: npm run start --workspace backend
    healthCheckPath: /api/schedule?date=2024-01-01
