import type { Scorecard, TeamScorecard, TeamTotals } from '@mlb-scorecards/shared';
import { formatFullDate } from '../lib/date';
import { getTeamColor } from '../teamColors';
import { LogoMark } from './Logo';
import { PitchingTable } from './PitchingTable';
import { ScorecardTable } from './ScorecardTable';

/** Compact self-documenting key so the printed card explains its own shorthand. */
const LEGEND: Array<[string, string]> = [
  ['K / ꓘ', 'strikeout (swinging / looking)'],
  ['6-3', 'groundout, SS to 1B'],
  ['F8', 'flyout to CF'],
  ['1B–7', 'single, fielded by LF'],
  ['BB', 'walk'],
  ['HR', 'home run'],
  ['SB', 'stolen base'],
  ['◇', 'bases reached (filled = scored)'],
];

function TeamBand({ team, totals, side }: { team: TeamScorecard; totals: TeamTotals; side: 'AWAY' | 'HOME' }) {
  const color = getTeamColor(team.team.id);
  return (
    <div className="print-team-band" style={{ borderLeft: `5px solid ${color.bg}` }}>
      <span className="print-team-band-side">{side}</span>
      <span className="print-team-band-name">{team.team.name}</span>
      <span className="print-team-band-line">
        {totals.r} R · {totals.h} H · {totals.e} E
      </span>
    </div>
  );
}

export function PrintScorecard({ scorecard }: { scorecard: Scorecard }) {
  const seasonYear = scorecard.date ? Number(scorecard.date.slice(0, 4)) : null;
  const statusLabel =
    scorecard.status.abstractGameState === 'Final'
      ? 'FINAL'
      : scorecard.status.abstractGameState === 'Live'
        ? `LIVE · ${scorecard.halfInning === 'top' ? '▲' : '▼'} ${scorecard.inning}`
        : scorecard.status.detailedState;

  const team = (side: 'away' | 'home') => (
    <section className="print-team" data-side={side}>
      <TeamBand
        team={scorecard.teams[side]}
        totals={scorecard.totals[side]}
        side={side === 'away' ? 'AWAY' : 'HOME'}
      />
      <ScorecardTable
        team={scorecard.teams[side]}
        linescore={scorecard.linescore}
        totals={scorecard.totals[side]}
        side={side}
        seasonYear={seasonYear}
      />
      <PitchingTable
        teamName={scorecard.teams[side].team.name}
        pitching={scorecard.teams[side].pitching}
        seasonYear={seasonYear}
      />
    </section>
  );

  return (
    <div className="print-scorecard">
      <header className="print-masthead">
        <div className="print-brand">
          <LogoMark size={30} />
          <span className="print-brand-name">MLB Live Scorecards</span>
        </div>
        <div className="print-title">
          <h1 className="print-matchup">
            {scorecard.teams.away.team.name} <span className="print-at">@</span> {scorecard.teams.home.team.name}
          </h1>
          <div className="print-sub">
            {scorecard.date ? formatFullDate(scorecard.date) : ''}
            {scorecard.venue ? ` · ${scorecard.venue}` : ''}
          </div>
        </div>
        <div className="print-scoreboard">
          <span className={`print-status${statusLabel === 'FINAL' ? ' print-status-final' : ''}`}>{statusLabel}</span>
          <table className="print-rhe">
            <thead>
              <tr>
                <th />
                <th>R</th>
                <th>H</th>
                <th>E</th>
              </tr>
            </thead>
            <tbody>
              {(['away', 'home'] as const).map((side) => (
                <tr key={side} className={side === 'home' ? 'print-rhe-home' : undefined}>
                  <td className="print-rhe-abbr">{scorecard.teams[side].team.abbreviation}</td>
                  <td className="print-rhe-runs">{scorecard.totals[side].r}</td>
                  <td>{scorecard.totals[side].h}</td>
                  <td>{scorecard.totals[side].e}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </header>

      {team('away')}
      {team('home')}

      <div className="print-legend">
        <span className="print-legend-title">Scoring key</span>
        {LEGEND.map(([code, meaning]) => (
          <span key={code} className="print-legend-item">
            <span className="print-legend-code">{code}</span> {meaning}
          </span>
        ))}
      </div>
      <div className="print-footer">
        Generated by MLB Live Scorecards · {new Date().toLocaleDateString('en-US', { dateStyle: 'medium' } as Intl.DateTimeFormatOptions)} · Data: MLB Stats API
      </div>
    </div>
  );
}
